import type { NextPage } from 'next'
import Image from 'next/image'
import Head from 'next/head'
import gif from "../public/assets/the-simpsons-hi.gif"
import styled from '@emotion/styled'

const WelcomeDiv = styled.div`
  height: 80vh;
  display: flex;
  justify-content: center;
  align-items: center;
`

const Wrapper = styled.div`
  padding: 5rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  & h2{
    margin: 1rem;
  }
  @media (max-width: 1000px) {
    & h2{
    font-size: 0.8rem;
  }
  }
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WelcomeDiv>
        <Wrapper>
          <Image
            src={gif}
            alt="The Simpsons"
            width={450}
            height={300}
            />
            <h2>
              This is the dashboard, you can navigate using nav chips.
            </h2>
          </Wrapper>
      </WelcomeDiv>
    </div>
  )
}

export default Home
